### ISSUE TITLE
Tibanna CWL conformance tests

### ISSUE THREAD

**Issue by minneker** [4dn-dcic/tibanna#248]
Hi there,

Does Tibanna have any CWL conformance tests? Like those found here, for example: http://ci.commonwl.org/

Thanks,
Robert

**Comment by SooLee** [comment]
@minneker Thank you for pointing out about the conformance test. We currently do not have CWL conformance tests, but we will definitely look into the conformance test in the future. Tibanna does not parse CWL directly, but uses `cwltool` so as long as the CWL works with `cwltool`, it should work with Tibanna - there are some exceptions related to file transfer to and from S3. e.g. Currently, it does not support transferring an output array to S3.

**Comment by minneker** [comment]
Thank you for your prompt reply!
