### ISSUE TITLE
Tibanna workflow for an AWS role

### ISSUE THREAD

**Issue by TMiguelT** [4dn-dcic/tibanna#250]
I'm attempting to run a SnakeMake workflow on AWS using tibanna, following the instructions [here](https://snakemake.readthedocs.io/en/stable/executable.html#executing-a-snakemake-workflow-via-tibanna-on-amazon-web-services).

I have an AWS project that has no IAM users. Instead, we have a role that all users (with sufficient permissions) can assume in order to access the project.

So while following the tutorial, I can get up to `tibanna deploy_unicorn -g tibanna -b my_tibanna_bucket`, but then I get stuck at `tibanna add_user -u <username> -g <name>`. Like I said, the project has no users, so this command doesn't make sense. Is there a way to add a role to the user group instead?

**Comment by SooLee** [comment]
@TMiguelT When you run `tibanna deploy_unicorn -g tibanna -b my_tibanna_bucket`, Tibanna creates a usergroup named `tibanna_<groupname>` (in your case it would be `tibanna_tibanna`) with all the necessary permissions. We don't currently have an automated way to support a non-user-based permission set-up, but you can manually go over the policies that are included in the tibanna usergroup and manually attach them to your role. Please let me know if this is not clear.

**Comment by TMiguelT** [comment]
Thanks, I can work with that.
