### ISSUE TITLE
Can Tibanna pull containers from the AWS Elastic Container Registry (ECR)?

### ISSUE THREAD

**Issue by tomsing1** [4dn-dcic/tibanna#280]
Thank a lot for making Tibanna available. I am using the [Elastic Container Registry](https://aws.amazon.com/ecr/) on AWS to store my (private) containers. 

Is Tibanna able to pull containers from ECR instead of dockerhub? (AWS Batch supports ECR out of the box.)

The main question, I believe, is whether a policy that grants access to ECR to the tibanna_<usergroup> AIM group can be added. And whether it is passed on to the EC2 instances Tibanna creates?

Many thanks for any thoughts,
Thomas

**Comment by SooLee** [comment]
@tomsing1 That's an interesting idea. Thank you for the suggestion. I can look into it today. Adding an IAM permission to the Tibanna instance is probably not very difficult. But it looks like you need to log into ECR from each machine before pulling an image? So, that should be added as an optional command if the user chooses to use ECR. Are you using CWL/WDL or shell?

**Comment by tomsing1** [comment]
Thanks a lot for looking into this option! You are correct that when you start an EC2 instance manually (e.g. outside of AWS Batch) then you have to log into ECR first. *But* within AWS Batch that seems to be unnecessary (see below).

I have been using AWS Batch (without Tibanna) for a while, but I am far from an expert. Here is what works for me:

I created an AWS Batch `Compute Environment` that manages an ECS Cluster cluster for me.
As part of the setup, I specified an "Instance role" that I created. This IAM role has two policies attached:

1. The preconfigured `AmazonEC2ContainerServiceforEC2Role` policy
2. A custom policy I created that allows access to ECR. 

Right now, the latter simply gives full access to ECR, but it could be constrained more:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt123456",
            "Action": "ecr:*",
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

When I submit jobs to AWS Batch, I simply specify the URL of a repository in ECR in the `image` section. That seems to be sufficient for the container instance to pull the image, e.g. I don't have to include any login commands in my jobs.

E.g. here is one of my job definitions:

```json
{
    "jobDefinitionName": "fastqc",
    "jobDefinitionArn": "arn:aws:batch:us-east-1:12345:job-definition/fastqc:1",
    "revision": 1,
    "status": "ACTIVE",
    "type": "container",
    "parameters": {},
    "containerProperties": {
        "image": "12345.dkr.ecr.us-east-1.amazonaws.com/ngs/fastqc",
        "vcpus": 1,
        "memory": 4000,
        "command": [
            "Ref::fq",
            "Ref::outdir"
        ],
        "ulimits": [],
        "resourceRequirements": []
    }
}
```

**Comment by tomsing1** [comment]
Oh, and I forgot to answer your question: I am not using CWL/WDL, although I might get there eventually. Right now I am most interested in running Snakemake workflows via Tibanna.

**Comment by SooLee** [comment]
@tomsing1 Thanks for the details! Would it make sense to assume that the ECR and the EC2 (and tibanna) are in the same region, or do you think you'd need a broader access to ECR? i.e. do you think you'll need access from `us-east-1` Tibanna/EC2 to `us-west-1` ECR?

**Comment by tomsing1** [comment]
So far, I have only accessed ECR in the same region that the EC2 instances were running in. So that would solve my use case!

**Comment by SooLee** [comment]
@tomsing1 Thank you, that made it easier. It should work with tibanna `0.18.0`. You need to redeploy it.

**Comment by tomsing1** [comment]
Awesome! Thank you so much for implementing this feature so quickly 🚀. I will try to deploy and test it as soon as I have the chance.
