### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by chandanbfx** [4dn-dcic/tibanna#283]
Hi,

snakemake = 5.17.0
tibanna = 0.18.0

I am trying to run snakemake workflow on AWS using tibanna. I followed the snakemake instructions to deploy tibanna unicorn and other setups. AWS credentials configured accordingly.

My dry run was successful:
$snakemake -np --use-conda  --tibanna --default-remote-prefix=extoolbackup/data
command output is as expected, and print all details I expected.

However, when I execute workflow:
$snakemake --use-conda  --tibanna --default-remote-prefix=extoolbackup/data
executions failed and the error message is "Couldn't get a file descriptor referring to the console".

Although I am successfully executed workflow locally.
$snakemake --use-conda --verbose --cores 4

I have attached the output of workflow run with --verbose and Snakefile as well.

[log.txt](https://github.com/4dn-dcic/tibanna/files/4608745/log.txt)
[Snakefile.txt](https://github.com/4dn-dcic/tibanna/files/4608818/Snakefile.txt)
[environment.yaml.txt](https://github.com/4dn-dcic/tibanna/files/4608771/environment.yaml.txt)

Thanks
Chandan

**Comment by SooLee** [comment]
@chandanbfx Can you tell whether the error message is coming from Snakemake or from Tibanna?

**Comment by chandanbfx** [comment]
Hi @SooLee  
I am not sure about the error from where it is throwing exactly. However, I successfully executed the workflow on a local machine, and when I tried to run a workflow using tibanna on AWS, then this error occurred.

**Comment by chandanbfx** [comment]
Hi @SooLee 

The issue occurred due to AWS's limited permission for the IAM user and get resolved when provided full access.

Now I am getting this error
errorMessage": "Not enough space for input files: download failed. And eventually, the execution failed.
logfile: 
[XTMjMnV5b2NW.log](https://github.com/4dn-dcic/tibanna/files/4615835/XTMjMnV5b2NW.log)

Any suggestion on how to configure EBS volume.

thanks
Chandan

**Comment by SooLee** [comment]
Great that the permission issue has been resolved. In general, you can add a user to the tibanna group by `tibanna add_user -u <user> -g <group>` which should give the appropriate permission to the user to run a workflow.

As to the disk space (EBS volume), have you tried the following?

```
resources:
        disk_mb=20000
```

**Comment by chandanbfx** [comment]
Thank  @SooLee  It's fixed the "no space" issue.
