### ISSUE TITLE
Cannot use cleanup when group starts with tibanna

### ISSUE THREAD

**Issue by klai5** [4dn-dcic/tibanna#288]
I made a group called tibannatest & as a result I cannot use tibanna cleanup because it assumes the group should not start with tibanna (lines 1127 & 1128 in core.py).

`if user_group_name.startswith('tibanna'):
            raise Exception("User_group_name does not start with tibanna or tibanna_unicorn."`

Maybe add an exception saying groups starting with "tibanna" or "tibanna_unicorn" cannot be deployed? Maybe another option is just seeing if tibanna_unicorn_[group] or [group] exists. Then proceed to cleanup?

**Comment by SooLee** [comment]
@klai5 I released `0.18.1`. Can you try again?
