### ISSUE TITLE
Issues with STAR alignment reading external files

### ISSUE THREAD

**Issue by jgoldst7** [4dn-dcic/tibanna#290]
Hello. I am currently running an RNAseq pipeline through the snakemake/tibanna framework. I am having trouble when it comes to the alignment step. My alignment steps keeps failing with the error 

"EXITING because of FATAL ERROR: could not open genome file /Users/jeremygoldstein/data/refseq/Homo_Sapien/STAR_index/genomeParameters.txt"
 However, when I run the exact same command on normal snakemake, the alignment works fine, which makes me think this is an issue with tibanna and not STAR. Attatched is my specific rule for STAR. 

Run with the command `<snakemake --cores>` The rule runs fine and produces the right output. However, with no change in the rule, the command `<snakemake --tibanna --default-remote-prefix=rnaseq.raw --use-conda>` results in the error mentioned above. Below is the error of the job run specifically. Any ideas on what might be causing this problem?

Fri May 29 21:46:35 UTC 2020
--2020-05-29 21:46:35--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf//aws_decode_run_json.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.64.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.64.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /4dn-dcic/tibanna/master/awsf/aws_decode_run_json.py [following]
--2020-05-29 21:46:35--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf/aws_decode_run_json.py
Reusing existing connection to raw.githubusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 12965 (13K) [text/plain]
Saving to: ‘aws_decode_run_json.py’

     0K .......... ..                                         100%  110M=0s

2020-05-29 21:46:36 (110 MB/s) - ‘aws_decode_run_json.py’ saved [12965/12965]

--2020-05-29 21:46:36--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf//aws_update_run_json.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.64.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.64.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /4dn-dcic/tibanna/master/awsf/aws_update_run_json.py [following]
--2020-05-29 21:46:36--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf/aws_update_run_json.py
Reusing existing connection to raw.githubusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 699 [text/plain]
Saving to: ‘aws_update_run_json.py’

     0K                                                       100% 67.6M=0s

2020-05-29 21:46:36 (67.6 MB/s) - ‘aws_update_run_json.py’ saved [699/699]

--2020-05-29 21:46:36--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf//aws_upload_output_update_json.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.64.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.64.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /4dn-dcic/tibanna/master/awsf/aws_upload_output_update_json.py [following]
--2020-05-29 21:46:36--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf/aws_upload_output_update_json.py
Reusing existing connection to raw.githubusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 9212 (9.0K) [text/plain]
Saving to: ‘aws_upload_output_update_json.py’

     0K ........                                              100%  108M=0s

2020-05-29 21:46:36 (108 MB/s) - ‘aws_upload_output_update_json.py’ saved [9212/9212]

--2020-05-29 21:46:36--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf//download_workflow.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.64.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.64.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /4dn-dcic/tibanna/master/awsf/download_workflow.py [following]
--2020-05-29 21:46:43--  https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf/download_workflow.py
Reusing existing connection to raw.githubusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 2076 (2.0K) [text/plain]
Saving to: ‘download_workflow.py’

     0K ..                                                    100% 58.8M=0s

2020-05-29 21:46:43 (58.8 MB/s) - ‘download_workflow.py’ saved [2076/2076]

rnaseq.raw
download: s3://rnaseq.raw/hIeV9EGFDIMF.run.json to ./hIeV9EGFDIMF.run.json
NAME        MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1     259:1    0   8G  0 disk 
└─nvme0n1p1 259:2    0   8G  0 part /
nvme1n1     259:0    0   1G  0 disk 
mke2fs 1.42.13 (17-May-2015)
Creating filesystem with 262144 4k blocks and 65536 inodes
Filesystem UUID: e1026635-9ac0-4cca-a000-18d050257869
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

main workflow file: Snakefile
workflow files: ['workflow/envs/fastQC-trimGalore.yaml', 'workflow/rules/trimGalore.smk', 'workflow/rules/STAR.smk', 'workflow/rules/fastQC.smk', 'workflow/envs/STAR.yaml', 'Snakefile']
downloading key hIeV9EGFDIMF.workflow/workflow/envs/fastQC-trimGalore.yaml from bucket rnaseq.raw to target /data1/snakemake/workflow/envs/fastQC-trimGalore.yaml
downloading key hIeV9EGFDIMF.workflow/workflow/rules/trimGalore.smk from bucket rnaseq.raw to target /data1/snakemake/workflow/rules/trimGalore.smk
downloading key hIeV9EGFDIMF.workflow/workflow/rules/STAR.smk from bucket rnaseq.raw to target /data1/snakemake/workflow/rules/STAR.smk
downloading key hIeV9EGFDIMF.workflow/workflow/rules/fastQC.smk from bucket rnaseq.raw to target /data1/snakemake/workflow/rules/fastQC.smk
downloading key hIeV9EGFDIMF.workflow/workflow/envs/STAR.yaml from bucket rnaseq.raw to target /data1/snakemake/workflow/envs/STAR.yaml
downloading key hIeV9EGFDIMF.workflow/Snakefile from bucket rnaseq.raw to target /data1/snakemake/Snakefile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152  100   152    0     0   6657      0 --:--:-- --:--:-- --:--:--  6909
100   617  100   617    0     0   2448      0 --:--:-- --:--:-- --:--:--  2448
100 13.3M  100 13.3M    0     0  28.7M      0 --:--:-- --:--:-- --:--:-- 28.7M
user_allow_other
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
if [[ -z $(aws s3 ls s3://rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq/ ) ]]; then aws s3 cp s3://rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq /data1/snakemake/rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq ;  else aws s3 cp --recursive s3://rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq /data1/snakemake/rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq ;  fi
if [[ -z $(aws s3 ls s3://rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq/ ) ]]; then aws s3 cp s3://rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq /data1/snakemake/rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq ;  else aws s3 cp --recursive s3://rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq /data1/snakemake/rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq ;  fi
Fri May 29 21:47:16 UTC 2020
Fri May 29 21:47:19 UTC 2020
aws_decode_run_json.py
aws_update_run_json.py
aws_upload_output_update_json.py
cromwell
download_command_list.txt
download_workflow.py
env_command_list.txt
goofys-latest
hIeV9EGFDIMF.run.json
mount_command_list.txt
Fri May 29 21:47:19 UTC 2020
Fri May 29 21:47:19 UTC 2020
aws_decode_run_json.py
aws_update_run_json.py
aws_upload_output_update_json.py
cromwell
download_command_list.txt
download_workflow.py
env_command_list.txt
goofys-latest
hIeV9EGFDIMF.run.json
mount_command_list.txt
Filesystem     1K-blocks    Used Available Use% Mounted on
udev            32658188       0  32658188   0% /dev
tmpfs            6533236    8644   6524592   1% /run
/dev/nvme0n1p1   8065444 2294780   5754280  29% /
tmpfs           32666176       0  32666176   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs           32666176       0  32666176   0% /sys/fs/cgroup
/dev/nvme1n1      999320    8116    922392   1% /data1
/home/ubuntu
total 108K
-rwxr-xr-x   1 root   root  15K May 29 21:46 aws_run_workflow_generic.sh
drwxr-xr-x   2 root   root 4.0K Oct 12  2018 bin
drwxr-xr-x   3 root   root 4.0K Oct 12  2018 boot
drwxr-xr-x   7 ubuntu root 4.0K May 29 21:46 data1
drwxr-xr-x  13 root   root 3.3K May 29 21:46 dev
drwxr-xr-x  99 root   root 4.0K May 29 21:47 etc
-rw-r--r--   1 root   root    0 May 29 21:46 hIeV9EGFDIMF.job_started
drwxr-xr-x   3 root   root 4.0K May 31  2018 home
lrwxrwxrwx   1 root   root   30 Oct 12  2018 initrd.img -> boot/initrd.img-4.4.0-1069-aws
lrwxrwxrwx   1 root   root   30 May 22  2018 initrd.img.old -> boot/initrd.img-4.4.0-1060-aws
drwxr-xr-x  21 root   root 4.0K May 31  2018 lib
drwxr-xr-x   2 root   root 4.0K May 22  2018 lib64
drwx------   2 root   root  16K May 22  2018 lost+found
drwxr-xr-x   2 root   root 4.0K May 22  2018 media
drwxr-xr-x   2 root   root 4.0K May 22  2018 mnt
drwxr-xr-x   2 root   root 4.0K May 22  2018 opt
dr-xr-xr-x 177 root   root    0 May 29 21:46 proc
drwx------   7 root   root 4.0K May 29 21:47 root
drwxr-xr-x  24 root   root  940 May 29 21:46 run
drwxr-xr-x   2 root   root  12K Oct 12  2018 sbin
drwxr-xr-x   2 root   root 4.0K May 31  2018 snap
drwxr-xr-x   2 root   root 4.0K May 22  2018 srv
dr-xr-xr-x  13 root   root    0 May 29 21:46 sys
drwxrwxrwt   8 root   root 4.0K May 29 21:47 tmp
drwxr-xr-x  10 root   root 4.0K May 22  2018 usr
drwxr-xr-x  13 root   root 4.0K May 22  2018 var
lrwxrwxrwx   1 root   root   27 Oct 12  2018 vmlinuz -> boot/vmlinuz-4.4.0-1069-aws
lrwxrwxrwx   1 root   root   27 May 22  2018 vmlinuz.old -> boot/vmlinuz-4.4.0-1060-aws
total 32K
drwxr-xr-x 2 root   root 4.0K May 29 21:46 input
drwx--x--x 2 ubuntu root  16K May 29 21:46 lost+found
drwxr-xr-x 2 root   root 4.0K May 29 21:46 out
drwxr-xr-x 2 root   root 4.0K May 29 21:46 reference
drwxr-xr-x 4 root   root 4.0K May 29 21:47 snakemake
/data1/input:
total 0
/data1/snakemake:
total 12K
drwxr-xr-x 3 root root 4.0K May 29 21:47 rnaseq.raw
-rw-r--r-- 1 root root 2.5K May 29 21:46 Snakefile
drwxr-xr-x 4 root root 4.0K May 29 21:46 workflow

/data1/snakemake/rnaseq.raw:
total 4.0K
drwxr-xr-x 3 root root 4.0K May 29 21:47 results

/data1/snakemake/rnaseq.raw/results:
total 4.0K
drwxr-xr-x 2 root root 4.0K May 29 21:47 trimming

/data1/snakemake/rnaseq.raw/results/trimming:
total 6.7M
-rw-r--r-- 1 root root 3.3M May 29 16:20 LCS7616_RR_C1_SEQ5_1_R1_val_1.fq
-rw-r--r-- 1 root root 3.3M May 29 16:20 LCS7616_RR_C1_SEQ5_1_R2_val_2.fq

/data1/snakemake/workflow:
total 8.0K
drwxr-xr-x 2 root root 4.0K May 29 21:46 envs
drwxr-xr-x 2 root root 4.0K May 29 21:46 rules

/data1/snakemake/workflow/envs:
total 8.0K
-rw-r--r-- 1 root root 100 May 29 21:46 fastQC-trimGalore.yaml
-rw-r--r-- 1 root root  79 May 29 21:46 STAR.yaml

/data1/snakemake/workflow/rules:
total 12K
-rw-r--r-- 1 root root  566 May 29 21:46 fastQC.smk
-rw-r--r-- 1 root root 1.9K May 29 21:46 STAR.smk
-rw-r--r-- 1 root root 1.1K May 29 21:46 trimGalore.smk
running snakemake rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.out.sam --snakefile Snakefile --force -j1 --keep-target-files --keep-remote --latency-wait 0 --attempt 1 --force-use-threads --allowed-rules STAR --nocolor --notemp --no-hooks --nolock --use-conda in docker image snakemake/snakemake:v5.14.0...
Unable to find image 'snakemake/snakemake:v5.14.0' locally
v5.14.0: Pulling from snakemake/snakemake
070ec86b6816: Pulling fs layer
c8e04ffeb25c: Pulling fs layer
153f09d1a5f5: Pulling fs layer
3e879c9d7f8f: Pulling fs layer
3e879c9d7f8f: Waiting
070ec86b6816: Verifying Checksum
070ec86b6816: Download complete
3e879c9d7f8f: Verifying Checksum
3e879c9d7f8f: Download complete
c8e04ffeb25c: Verifying Checksum
c8e04ffeb25c: Download complete
070ec86b6816: Pull complete
c8e04ffeb25c: Pull complete
153f09d1a5f5: Verifying Checksum
153f09d1a5f5: Download complete
153f09d1a5f5: Pull complete
3e879c9d7f8f: Pull complete
Digest: sha256:08c79287e8e2ca9ebe5dd2d800f4c424e44f7bb3e1de29f39a0002c14f2e0703
Status: Downloaded newer image for snakemake/snakemake:v5.14.0
Building DAG of jobs...
Creating conda environment workflow/envs/STAR.yaml...
Downloading and installing remote packages.
top - 21:48:01 up 1 min,  0 users,  load average: 1.58, 0.62, 0.23
Tasks: 178 total,   3 running, 175 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.6 us,  5.3 sy,  0.3 ni, 83.0 id,  2.6 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 65332352 total, 61870388 free,   628820 used,  2833144 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 64136340 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7514 root      20   0  724856 232908  11708 S 100.0  0.4   0:06.07 conda-env
 7534 root      20   0   65220  21112   4660 R  75.0  0.0   0:00.13 mon-put-in+
 7535 root      20   0   65180  21252   4700 R  75.0  0.0   0:00.13 mon-put-in+
    1 root      20   0   38028   6048   4020 S   0.0  0.0   0:02.13 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/0
    4 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+
4.0K    /data1/input/
4.0K    /data1/tmp/
20K     /data1/out/
Environment for workflow/envs/STAR.yaml created (location: .snakemake/conda/a54d8bc7)
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       STAR
        1

[Fri May 29 21:48:30 2020]
Job 0: ...Aligning LCS7616_RR_C1_SEQ5_1 with STAR two-pass...please wait...

Activating conda environment: /data1/snakemake/.snakemake/conda/a54d8bc7
[Fri May 29 21:48:31 2020]
Error in rule STAR:
    jobid: 0
    output: rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.out.sam, rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Log.final.out, rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.toTranscriptome.out.bam, rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Chimeric.out.junction
    log: rnaseq.raw/logs/alignment/LCS7616_RR_C1_SEQ5_1.log (check log file(s) for error message)
    conda-env: /data1/snakemake/.snakemake/conda/a54d8bc7
    shell:
        
                STAR --genomeDir /Users/jeremygoldstein/data/refseq/Homo_Sapien/STAR_index              --runThreadN 4          --readFilesIn rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq                --outFileNamePrefix rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/                 --outReadsUnmapped None                 --twopassMode Basic             --outSAMunmapped Within                --chimSegmentMin 12             --chimJunctionOverhangMin 8             --chimOutJunctionFormat 1               --alignSJDBoverhangMin 10              --alignMatesGapMax 100000               --alignIntronMax 100000                 --alignSJstitchMismatchNmax 5 -1 5 5          --chimMultimapScoreRange 3               --chimScoreJunctionNonGTAG -4           --chimMultimapNmax 20           --chimNonchimScoreDropMin 10          --peOverlapNbasesMin 12          --peOverlapMMp 0.1              --alignInsertionFlush Right             --alignSplicedMateMapLminOverLmate 0          --alignSplicedMateMapLmin 30             --quantMode TranscriptomeSAM            --quantTranscriptomeBan IndelSoftclipSingleend          --outSAMmapqUnique 60 &> rnaseq.raw/logs/alignment/LCS7616_RR_C1_SEQ5_1.log
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Uploading to remote: rnaseq.raw/logs/alignment/LCS7616_RR_C1_SEQ5_1.log
Finished upload.
Removing output files of failed job STAR since they might be corrupted:
rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R1_val_1.fq, rnaseq.raw/results/trimming/LCS7616_RR_C1_SEQ5_1_R2_val_2.fq, rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.out.sam, rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.toTranscriptome.out.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data1/snakemake/.snakemake/log/2020-05-29T214754.346910.snakemake.log
Snakefile is being executed!
The following are the raw samples
 ['LCS7616_RR_C1_NT_1', 'LCS7616_RR_C1_NT_2', 'LCS7616_RR_C1_NT_3', 'LCS7616_RR_C1_SEQ5_1', 'LCS7616_RR_C1_SEQ5_2', 'LCS7616_RR_C1_SEQ5_3']

With the following criterion
cell lines:  ['C1'] 
treatments:  ['NT', 'SEQ5'] 
replicates:  ['1', '2', '3'] 
reads:  ['R1', 'R2']
Fri May 29 21:48:33 UTC 2020
/data1/out/:
total 20K
-rw-r--r-- 1 root   root   0 May 29 21:48 hIeV9EGFDIMF.error
-rw-r--r-- 1 root   root  64 May 29 21:48 hIeV9EGFDIMF.md5sum.txt
-rwxr-xr-x 1 ubuntu root 16K May 29 21:48 hIeV9EGFDIMF.log
total 36K
drwx--x--x 2 ubuntu root  16K May 29 21:46 lost+found
drwxr-xr-x 2 root   root 4.0K May 29 21:46 reference
drwxr-xr-x 2 root   root 4.0K May 29 21:46 input
drwxr-xr-x 2 root   root 4.0K May 29 21:47 tmp
drwxr-xr-x 5 root   root 4.0K May 29 21:47 snakemake
drwxr-xr-x 2 root   root 4.0K May 29 21:48 out
/data1/input/:
total 0
/data1/snakemake/:
total 12K
drwxr-xr-x 4 root root 4.0K May 29 21:46 workflow
-rw-r--r-- 1 root root 2.5K May 29 21:46 Snakefile
drwxr-xr-x 4 root root 4.0K May 29 21:48 rnaseq.raw

/data1/snakemake/workflow:
total 8.0K
drwxr-xr-x 2 root root 4.0K May 29 21:46 rules
drwxr-xr-x 2 root root 4.0K May 29 21:46 envs

/data1/snakemake/workflow/rules:
total 12K
-rw-r--r-- 1 root root 1.1K May 29 21:46 trimGalore.smk
-rw-r--r-- 1 root root 1.9K May 29 21:46 STAR.smk
-rw-r--r-- 1 root root  566 May 29 21:46 fastQC.smk

/data1/snakemake/workflow/envs:
total 8.0K
-rw-r--r-- 1 root root 100 May 29 21:46 fastQC-trimGalore.yaml
-rw-r--r-- 1 root root  79 May 29 21:46 STAR.yaml

/data1/snakemake/rnaseq.raw:
total 8.0K
drwxr-xr-x 3 root root 4.0K May 29 21:48 logs
drwxr-xr-x 3 root root 4.0K May 29 21:48 results

/data1/snakemake/rnaseq.raw/logs:
total 4.0K
drwxr-xr-x 2 root root 4.0K May 29 21:48 alignment

/data1/snakemake/rnaseq.raw/logs/alignment:
total 4.0K
-rw-r--r-- 1 root root 402 May 29 21:48 LCS7616_RR_C1_SEQ5_1.log

/data1/snakemake/rnaseq.raw/results:
total 4.0K
drwxr-xr-x 3 root root 4.0K May 29 21:48 alignment

/data1/snakemake/rnaseq.raw/results/alignment:
total 4.0K
drwxr-xr-x 5 root root 4.0K May 29 21:48 LCS7616_RR_C1_SEQ5_1

/data1/snakemake/rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1:
total 32K
drwx------ 2 root root 4.0K May 29 21:48 _STARtmp
drwx------ 2 root root 4.0K May 29 21:48 _STARpass1
drwx------ 2 root root 4.0K May 29 21:48 _STARgenome
-rw-r--r-- 1 root root    0 May 29 21:48 Log.progress.out
-rw-r--r-- 1 root root  20K May 29 21:48 Log.out

/data1/snakemake/rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/_STARtmp:
total 0

/data1/snakemake/rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/_STARpass1:
total 0

/data1/snakemake/rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/_STARgenome:
total 0
Traceback (most recent call last):
  File "./aws_upload_output_update_json.py", line 157, in <module>
    raise Exception("output file {} upload to {} failed. %s".format(source, bucket + '/' + target) % e)
Exception: output file /data1/snakemake/rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.out.sam upload to rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.out.sam failed. [Errno 2] No such file or directory: '/data1/snakemake/rnaseq.raw/results/alignment/LCS7616_RR_C1_SEQ5_1/Aligned.out.sam'
Filesystem      Size  Used Avail Use% Mounted on
udev             32G     0   32G   0% /dev
tmpfs           6.3G  8.5M  6.3G   1% /run
/dev/nvme0n1p1  7.7G  4.3G  3.5G  56% /
tmpfs            32G     0   32G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/nvme1n1    976M   11M  899M   2% /data1

[STAR.txt](https://github.com/4dn-dcic/tibanna/files/4704563/STAR.txt)

**Comment by SooLee** [comment]
@jgoldst7 Was /Users/jeremygoldstein/data/refseq/Homo_Sapien/STAR_index/genomeParameters.txt" specified as an input file in the snakefile? To use tibanna, everything you need must be soexified as input, otherwise they will not be copied to the instance.

**Comment by jgoldst7** [comment]
Hello, thanks for the response. I figured out that things in the "params" section don't get copied into the instance, that was my issue. My question then becomes, for tools that use an index, which in essence is a folder with a bunch of files, is the only way to make this to work to specify all of those files as input files? 
Because I believe you can't name a folder as input, it has to be a file. Attached
[STAR.txt](https://github.com/4dn-dcic/tibanna/files/4712030/STAR.txt)
 below is my updated rule, which works, but I was wondering if this was the only solution, or there was a workaround where I could name a folder that would be uploaded to the EC2 instance?

**Comment by SooLee** [comment]
We do have folder support on Tibanna. If Snakemake allows input folders, we can add that feature to Snakemake-Tibanna.

**Comment by SooLee** [comment]
Another way is to zip the folder and unzip it as part of the rule?

**Comment by jgoldst7** [comment]
I will feature request Snakemake about allowing input folders then but in the meantime, zipping the folder is a good work around. Thanks for the help!
