### ISSUE TITLE
Job fails without error message

### ISSUE THREAD

**Issue by nhartwic** [4dn-dcic/tibanna#291]
Well, I'm back. Everything seemed to be working so well. Workflow worked perfectly on several datasets. On a particularly large dataset, my workflow is now failing without an error message after running for about three days. output and log below...

[wm7004.log1.txt](https://github.com/4dn-dcic/tibanna/files/4715081/wm7004.log1.txt)
[wm7004.out1.txt](https://github.com/4dn-dcic/tibanna/files/4715082/wm7004.out1.txt)

Just like last time, it seems to be the idle instance detection that is biting me. Last couple real entries including error from cloudwatch below...

```

2020-05-30T14:45:30.508-07:00
2020-05-30T21:45:30.508Z e0b9a9bb-6394-44c2-8f09-b03806e1f618	{'instance_id': 'i-0f34a53ae2e553cca', 'filesystem': '/dev/nvme1n1', 'client': <botocore.client.CloudWatch object at 0x7ff5cfbd1ef0>, 'starttimes': [datetime.datetime(2020, 5, 30, 20, 45, 29, 693085, tzinfo=tzutc())], 'endtimes': [datetime.datetime(2020, 5, 31, 20, 45, 29, 693085, tzinfo=tzutc())], 'start': datetime.datetime(2020, 5, 30, 20, 45, 29, tzinfo=tzutc()), 'end': datetime.datetime(2020, 5, 30, 21, 45, 29, tzinfo=tzutc()), 'nTimeChunks': 1, 'list_files': [], 'starttime': datetime.datetime(2020, 5, 30, 20, 45, 29, 693085, tzinfo=tzutc()), 'endtime': datetime.datetime(2020, 5, 31, 20, 45, 29, 693085, tzinfo=tzutc()), 'max_mem_used_MB': 57764.3828125, 'min_mem_available_MB': 5531.6875, 'total_mem_MB': 63296.0703125, 'max_mem_utilization_percent': 91.26061464370629, 'max_cpu_utilization_percent': '', 'max_disk_space_utilization_percent': 13.0300469215003, 'max_disk_space_used_GB': 62.7008895874023, 'max_ebs_read_bytes': ''}

2020-05-30T14:45:30.801-07:00
not enough arguments for format string: TypeError Traceback (most recent call last): File "/var/task/service.py", line 19, in handler return check_task(event) File "/var/task/tibanna/check_task.py", line 33, in check_task return CheckTask(input_json).run() File "/var/task/tibanna/check_task.py", line 124, in run cw_res['max_ebs_read_bytes']) File "/var/task/tibanna/check_task.py", line 142, in terminate_idle_instance jobid, str(cpu), str(e) TypeError: not enough arguments for format string
```

I launched this unicorn using a pip installed version of tibanna 0.18.0 which is older than my pull request that fixed this error formatting.

All this said, I basically have three questions I'm looking for help with...

1. If I clone your repo, which includes my updates to this error reporting, is there any way to easily update the step functions on aws? Last time around, I just redeployed a new unicorn which works but it bifurcates my job history and results in even more step functions being on aws to manage

2. Whenever I try to run 'plot_metrics' on a job that has finished for more than a couple hours, I get the following error. Any idea what causes it?

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/snake/bin/tibanna", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/snake/lib/python3.6/site-packages/tibanna/__main__.py", line 437, in main
    subcommandf(*sc_args)
  File "/home/ubuntu/miniconda3/envs/snake/lib/python3.6/site-packages/tibanna/__main__.py", line 382, in plot_metrics
    endtime=endtime, open_browser=not do_not_open_browser)
  File "/home/ubuntu/miniconda3/envs/snake/lib/python3.6/site-packages/tibanna/core.py", line 1005, in plot_metrics
    raise Exception("instance id not available for this run.")
Exception: instance id not available for this run.
```

3. any idea why my job would be crashing in a way that triggers the idle instance checks? The job ran for several days without issue.

**Comment by SooLee** [comment]
@nhartwic Your change is in 0.18.1. You can deploy individual lamdba functions to avoid deploying more unicorns.

```
tibanna deploy_core -n run_task_awsem [-g group] [-s suffix] 
tibanna deploy_core -n check_task_awsem [-g group] [-s suffix] 
```
2. Can you check your dynamoDB tibanna-master table from Console? I'm suspecting that the instance ID somehow didn't get in to the dynamoDB table.

3. Were you using a spot instance by any chance?

**Comment by nhartwic** [comment]
3. Spot_instance option is set to false. Full json describing job below..

```
[INFO] 2020-05-27T23:36:34.874Z 4beacb1a-e167-456c-ba60-ca3f4129ba86 jsonbody= { "Job": { "App": { "App_name": "", "App_version": "", "command": "snakemake Wm7004_male_v1.fasta.mod.EDTA.TEanno.gff --snakefile Snakefile --force -j16 --keep-target-files --keep-remote --latency-wait 0 --attempt 1 --force-use-threads --config ref=Wm7004_male_v1.fasta busco=viridiplantae gene_prefix=Wm7004 augustus_species=maize sra_short=SRR5894351,SRR8138861,ERR364404 threads=16 --allowed-rules edta --nocolor --notemp --no-hooks --nolock --use-conda ", "container_image": "snakemake/snakemake:v5.17.0", "language": "snakemake", "main_snakemake": "Snakefile", "other_snakemake_files": "envs/fun.yml,envs/edta.yml,envs/eggnog.yml,README.md,envs/transcript_assembly.yml", "snakemake_url": "s3://salk-tm-logs/69i57oGmkMnw.workflow/" }, "Input": { "Env": {}, "Input_files_data": { "file:///data1/snakemake/Wm7004_male_v1.fasta": { "class": "File", "dir": "salk-tm-fin", "mount": "", "path": "WelwitschiaLog Bucket, "Secondary_files_data": {} }, "JOBID": "69i57oGmkMnw", "Log": { "log_bucket_directory": "salk-tm-logs" }, "Output": { "alt_cond_output_argnames": {}, "output_bucket_directory": "salk-tm-fin", "output_target": { "file:///data1/snakemake/Wm7004_male_v1.fasta.mod.EDTA.TEanno.gff": "s3://salk-tm-fin/Welwitschia/Wm7004/Wm7004_male_v1.fasta.mod.EDTA.TEanno.gff", "file:///data1/snakemake/Wm7004_male_v1.fasta.mod.EDTA.TEanno.sum": "s3://salk-tm-fin/Welwitschia/Wm7004/Wm7004_male_v1.fasta.mod.EDTA.TEanno.sum", "file:///data1/snakemake/Wm7004_male_v1.fasta.mod.EDTA.TElib.fa": "s3://salk-tm-fin/Welwitschia/Wm7004/Wm7004_male_v1.fasta.mod.EDTA.TElib.fa" }, "secondary_output_target": {} }, "start_time": "20200527-23:36:34-UTC" }, "config": { "EBS_optimized": true, "ami_id": "ami-05bcbe2628605a628", "availability_zone": "", "behavior_on_capacity_limit": "fail", "cloudwatch_dashboard": false, "cpu": 16, "ebs_iops": "", "ebs_size": 489, "ebs_type": "gp2", "instance_type": "m5a.4xlarge", "job_tag": "", "json_bucket": "salk-tm-logs", "language": "snakemake", "log_bucket": "salk-tm-logs", "mem": 64.0, "public_postrun_json": false, "root_ebs_size": 16, "run_name": "snakemake-job-69i57oGmkMnw-rule-edta", "script_url": "https://raw.githubusercontent.com/4dn-dcic/tibanna/master/awsf/", "security_group": "", "shutdown_min": "now", "spot_duration": "", "spot_instance": false, "subnet": "" } }
```

2. Is there a reccomended way to check the dynamoDB? I just went into the aws dynomaDB web interface and found the relvant table. The following information is available for the job in question...

Execution Name : snakemake-job-69i57oGmkMnw-rule-edta
Job Id : 69i57oGmkMnw
Log Bucket : salk-tm-logs
Step Function : tibanna_unicorn_salk-tm-3
Time Stamp : 20200527-23:36:33-UTC

...Is there supposed to be more information?

**Comment by SooLee** [comment]
Ok, I asked because spot instances get interrupted if they run for a long time.
Can you install `0.18.3` and try plot_metrics with instance_id?
```
tibanna plot_metrics -j <job_id> -i <instance_id>
```
DynamoDB should have instance_id field. Somehow it didn't get in.

**Comment by nhartwic** [comment]
I don't think any of my DynamoDB entries have instance_id fields.

plot_metrics works when I gave it the instance ID. Output below...

https://salk-tm-logs.s3.amazonaws.com/69i57oGmkMnw.metrics/metrics.html

...Something weird seems to be happening at the tail end of the job. I'm repeatedly bumping up against memory limits while cpu usage goes down. The job log doesn't seem to agree on cpu usage though. Job log indicates that cpu usage varied from 50% to 60% throughout. Are these somehow consistent?

**Comment by SooLee** [comment]
Hmm.. I can look into the dynamoDB issue and the CPU usage discrepancy. In the mean time, it looks like there was a memory limit problem in your run (you need a machine with more memory to run this job).

**Comment by nhartwic** [comment]
Agreed. Well, nothing to do be retry with more memory I suppose. Thanks for the tip with plot_metrics. Let me know if there is anything I can do related to the dynamoDB issue.

Now that I'm on tibanna 1.8.3, I should get a more informative error message if it does fail again which is nice.

**Comment by SooLee** [comment]
It also looks like there were two different processes - one with low memory and another with higher memory near the end. You could maybe decouple those two (if possible) and run them as separate steps on different machines?

**Comment by nhartwic** [comment]
Doing so would require basically reimplementing the tool I'm currently using. (made by someone else) I'd rather not go down that route.

**Comment by nhartwic** [comment]
Well, it was definitely a memory issue. Thanks for the help with everything
