### ISSUE TITLE
Job fails even though it was actually successful

### ISSUE THREAD

**Issue by jgoldst7** [4dn-dcic/tibanna#292]
Hello,

I have been running a snakemake workflow through tibanna, and have been having the strange issue of a job failing with no indication as to why it failed. WHen I look at the runs log, there are no errors and everything seems successful, and the output files appeared in the S3 bucket, but I am curious as to why it is saying it is failing. Attatched is the log file of a run that says it failed. I also attached the lamda log. 
[lamda.log](https://github.com/4dn-dcic/tibanna/files/4731960/lamda.log)
When I looked at the log for the tool there are also no errors. Any advice on what is going on?
[eMxeZbpJjp9V.log](https://github.com/4dn-dcic/tibanna/files/4731910/eMxeZbpJjp9V.log)

**Comment by SooLee** [comment]
Hi @jgoldst7 It looks to me that you ran out of space. Can you try running `tibanna plot_metrics -j <jobid>`?

**Comment by SooLee** [comment]
The Key error problem when there is a very long postrun json (e.g due to many long commands) has been fixed in the later tibanna version. What version did you use to deploy unicorn?

**Comment by jgoldst7** [comment]
Attatched is the metrix report. My tibanna version is 0.18.0. I have run out of memory before but it usually shows up in the log for the run, so I didn't think that was the issue
[metrics_report.txt](https://github.com/4dn-dcic/tibanna/files/4732047/metrics_report.txt)

**Comment by SooLee** [comment]
The fix is in `0.18.2`. Can you redeploy your lambda?
```
tibanna deploy_core -n check_task_awsem [-g group] [-s suffix]
```

If you'r using the same file 6 times, it should still be one file so it should take up only 50Gb not 300G. Actually, according to the log you're using 48GB and all the output files were uploaded. So it didn't exceed the space limit. I'm guessing mostly it's the version problem. Can you retry it with `0.18.2`?

**Comment by jgoldst7** [comment]
WHere is version 0.18.2? The most recent version on condo is 0.18.0

**Comment by SooLee** [comment]
I don't think it ran out of space, though it would still be safer to increase the space a little bit.

You can redeploy just the lambda as below:
```
tibanna deploy_core -n check_task_awsem [-g group] [-s suffix]
```

**Comment by jgoldst7** [comment]
Sorry for the confusion in terminology, the lamda is that specific group, So if I have a single rule that is group: "fusion" and should run 6 times. and I were to do tibanna deploy_core -n check_task_awsem -g "fusion", it would run just that group?

**Comment by SooLee** [comment]
Ah, sorry for not being clear. The `group` here means the tibanna `user group` (not snakemake rule group) that you used when you deployed tibanna. The group is for a group of users sharing the same bucket and other permissions assigned to a specific tibanna unicorn. If you used the `-g` option when you ran `tibanna deploy_unicorn`, then the same value should be used here (similar to the `-s` option). If you didn't use the `-g` option when you deployed unicorn, then no need to specify it here as well.

**Comment by jgoldst7** [comment]
Got it, so I normally run my command `snakemake --tibanna --default-remote-prefix=rnaseq.raw --use-conda`. What you are recommending would do the same thing, or something different? By the way, updated to the tibanan 0.18.2 and am currently running again, but I had already started this run with my above command before I saw your response as to what command I should try.

**Comment by SooLee** [comment]
You can use the same command. Did you deploy the lambda before you started the rerun?

**Comment by jgoldst7** [comment]
Im sorry I am still confused, what is the difference between deploying the lambda and starting the rerun? I got the same issue. output files were there, log for the tool was fine, log for the run was fine. Below is the metrics for the run and there is still that key error problem
[metrics.txt](https://github.com/4dn-dcic/tibanna/files/4732323/metrics.txt)

**Comment by SooLee** [comment]
Lambda is a part of unicorn. The updated unicorn must be deployed on AWS before running any job. You have to be an admin in order to deploy/redeploy a lambda function. Did you use the `-g` option?

**Comment by jgoldst7** [comment]
So I made a new unicorn using the new version of tibanna with `tibanna deploy_unicorn -g shepRNAseq -b rnaseq.raw`. And then ran `snakemake --tibanna --default-remote-prefix=rnaseq.raw --use-conda`. It is currently running. Was this the right thing to do?

**Comment by SooLee** [comment]
Did you source `.bashrc` afterward? What do you see if you do
```
echo $TIBANNA_DEFAULT_STEP_FUNCTION_NAME
```

**Comment by jgoldst7** [comment]
yes I did, and the run completed successfully! So the lamba is always the same, and set with the deploy_unicorn command, regardless of what runs I am doing. That is why it didn't work after updating tibanna. I still was using the same lambda(unicorn) that was made with the older version of tibanna

**Comment by SooLee** [comment]
Glad it worked!

**Comment by jgoldst7** [comment]
Thank you so much for helping out!
