### ISSUE TITLE
Job fails without error message

### ISSUE THREAD

**Issue by jgoldst7** [4dn-dcic/tibanna#293]
Hello, back again. I have an issue where my jobs are failing with an AWSEMJobErrorException error. However, the output files are being correctly produced and stored, so it doesn't seem like there is anything actually wrong. I looked at the metrics and it wasn't an issue of running out of memory. The only thing that looks wrong in the job log is this line `"Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password"`. Would you mind taking a log at the job log and letting me know if that error could be causing the job error, or it is something else? When I run the command with snakemake locally, with the input and output files in the same s3 buckets, there are no issues. 

The metadata for the output files indicates that they are complete, because if I try to run a rule that depends on them, I don't any "incomplete files" error that usually occurs if an output file is tagged as incomplete in the metadata. So all senses the run seems to be successful, besides the fact that it says it fails. My current workaround has been to use the -k option with snakemake to ignore a failed job and keep going. But this makes me unable to group my jobs and obviously isn't exactly a solution to the problem.

Also every job seems to run for about 5 minutes before failing, if that helps. Thanks
[runlog.txt](https://github.com/4dn-dcic/tibanna/files/4742253/runlog.txt)

**Comment by SooLee** [comment]
AWS changed something and all runs are failing. I'll work on it today and get back to you.

**Comment by jgoldst7** [comment]
Thank you. It randomly started working again late last night, without me changing my code. So I am not sure what AWS changed but I am not longer getting those errors! I would still be interested to see how to go about debugging something like this if it happened in the future.

**Comment by SooLee** [comment]
Are you not getting this error?
```
An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: ... is not authorized to perform: ecr:GetAuthorizationToken on resource: *
```

**Comment by jgoldst7** [comment]
I was not getting that error. The job logs all looked like what I sent above. No real errors I could see besides ""Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password". Looking at the step function console. It would always run for 5 minutes. giving EC2startingexceptions because it would still booting, and then fail with an AWSEMJobErrorException saying to check the job log. But sometimes the log was showing that the file was uploaded successfully, even though the job failed

**Comment by SooLee** [comment]
@jgoldst7 Thanks, that was useful info! Good that it worked. The last problem turned out to be one in our system which happened coincidentally. The root of the problem was the urllib3 update which caused version conflict with cwltool and while I tried to resolve it I accidentally put awscli version to an older one which did not support ECR and caused an error temporarily. I had this additional error on my side and thought it was something else caused by a change in AWS requiring an additional IAM permission. It was not the case. Anyway, sorry for the inconvenience!

**Comment by jgoldst7** [comment]
Thanks for working on it and getting back to me! You've been very helpful with the issues I have been having.
