### ISSUE TITLE
Can ebs_size get increased via the snakemake command?

### ISSUE THREAD

**Issue by klai5** [4dn-dcic/tibanna#294]
Majority of the time, I work with relatively small bcl folders. Sometimes I have very large bcl folders that I want to download. Currently I specify a disk_mb in the snakemake rule. How do you recommend increasing the size of disk_mb when data grows? Can I do something like --tibanna-config ebs_size=10*{resources.disk_mb}?  I know from your documentation: It can be provided in the format of x (e.g. 3x, 5.5x) to request x times total input size, however directories do not work as inputs or outputs (issue: https://github.com/snakemake/snakemake/issues/355).

**Comment by nhartwic** [comment]
Are you trying to change the size of the root ebs or the size of the workspace ebs? If the latter, then you probably don't need to do anything. Snakemake/Tibanna will use the disk_mb set in resources when spinning up an AWS node. If the former, then you will need to get the latest version of snakemake from git and launch your tibanna jobs using the updated version and with "--tibanna-config root_ebs_size=32"
