### ISSUE TITLE
Pip alert when running deploy_unicorn

### ISSUE THREAD

**Issue by rdavison** [4dn-dcic/tibanna#303]
Just now I ran `tibanna deploy_unicorn`, and, while it completed successfully, it did emit an Error that might be relevant.  Just posting it here, in case you would like to investigate it. For all I know, maybe this isn't a problem with tibanna, but could be a problem with some packages upstream?

>ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
>
>We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

**Comment by SooLee** [comment]
Hi @rdavison, Thanks for reporting this problem. Are you using pip 20.0? They say they will release 20.3 in October which has this 2020 resolver as a default. I could not replicate the problem with Python 3.6 and pip 10.0.1, so maybe lowering the pip version could help it in the mean time.
