### ISSUE TITLE
Tibanna jobs failing unintendedly 

### ISSUE THREAD

**Issue by nhartwic** [4dn-dcic/tibanna#305]
Every tibanna job I kick off runs for about five minutes and then dies. This started happening some time in the last week to all of my snakemake workflows as that is the last time I tried to run some jobs. I'm having trouble figuring out what is going wrong.

I've attached the tibanna log for the job even though I don't see anything informative in it : [log_hSpIncnfdaf1.txt](https://github.com/4dn-dcic/tibanna/files/5421195/log_hSpIncnfdaf1.txt)

Cloudwatch logs were a bit more interesting. Seems like everything is going normally and then this error shows up.

```
EC2 is terminated unintendedly for job hSpIncnfdaf1 - please rerun.: EC2UnintendedTerminationException
Traceback (most recent call last):
  File "/var/task/service.py", line 19, in handler
    return check_task(event)
  File "/var/task/tibanna/check_task.py", line 33, in check_task
    return CheckTask(input_json).run()
  File "/var/task/tibanna/check_task.py", line 108, in run
    raise EC2UnintendedTerminationException(errmsg)
tibanna.exceptions.EC2UnintendedTerminationException: EC2 is terminated unintendedly for job hSpIncnfdaf1 - please rerun.
```

**Comment by SooLee** [comment]
Thanks for reporting this. We're having the same problem and trying to figure it out as well. I will definitely keep you posted.

**Comment by nhartwic** [comment]
Well, I'm reasonably confident none of my setup changed. The problem seems to be resolved though. Workflows are running successfully anyway. Must have been some transient issue with AWS itself. Very strange.
