### ISSUE TITLE
Tibanna1.0 errors out with Snakemake

### ISSUE THREAD

**Issue by klai5** [4dn-dcic/tibanna#328]
Running the latest version of snakemake (v6.0.5) and tibanna (v1.1.2) will result in an error that didn't exist with 0.18.3:

"tibanna.exceptions.MissingFieldInInputJsonException: field snakemake_main_filename is required in args for language snakemake"

It seems like it doesn't use the -s [snakefile] as the snakemake_main_filename?

**Comment by SooLee** [comment]
@klai5 Thanks for reporting the error. Tibanna v1.2.0 should work.
