### ISSUE TITLE
Log Differences between 0.18.3 and 1.0+

### ISSUE THREAD

**Issue by klai5** [4dn-dcic/tibanna#344]
Hello,

The old logs in v0.18.3 let me see all the files located on the server (e.g everything under /data1/snakemake). Is this missing from the new version?

Thanks!

**Comment by SooLee** [comment]
@klai5 That may be the case indeed. It was intended to produce a cleaner log, but looks like it's missing some info that could be useful. Sorry about the trouble and I will try to add it back in the next couple of days. Thanks for the ticket!

**Comment by klai5** [comment]
Thanks! Yeah, sometimes I would like to see what's on the instance during errors (e.g if it didn't download S3 files to the correct location) without having to ls -R on /data1/snakemake for every rule. Appreciate the help!

**Comment by SooLee** [comment]
@klai5 Sorry for the delay. The log should include the directory contents from 1.4.1 now.
