### ISSUE TITLE
Docker image for 1.9.2 doesn't exist

### ISSUE THREAD

**Issue by klai5** [4dn-dcic/tibanna#364]
When running the latest version of tibanna, I get the following error:

## Pulling Docker image
Error response from daemon: manifest for 4dndcic/tibanna-awsf:1.9.2 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for 4dndcic/tibanna-awsf:1.9.2 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for 4dndcic/tibanna-awsf:1.9.2 not found: manifest unknown: manifest unknown

It doesn't look like the container exists?

**Comment by alexander-veit** [comment]
Sorry about that! I pushed the new image to DockerHub. It should work now.
