### ISSUE TITLE
Large amounts of NAT gateway costs

### ISSUE THREAD

**Issue by laurentiush** [4dn-dcic/tibanna#397]
Hi, I am using Tibanna together with Snakemake and it seems that I am incurring large amounts of NAT gateway costs. It seems to be coming from EC2 instances downloading tibanna and snakemake everytime that an EC2 instance is created.

Is there a way to provide those packages/containers from my local cloud environment instead of taking them from the internet? Like this using tibanna and snakemake is prohibitively expensive.

**Comment by laurentiush** [comment]
I think I solved it by pushing the tibanna docker to my ECR and pointing tibanna to it by using the awsf_image parameter.

**Comment by willronchetti** [comment]
That is the solution that we use internally to run Tibanna at high scale, yes. We haven't used Dockerhub in some time not just for this reason but others as well.

**Comment by laurentiush** [comment]
Ah, good to hear that you are using that solution as well. I am having a similar issue with conda environments. Is it possible to provide a 'local' snakemake conda environment instead of downloading it from bioconda/conda-forge every time?

Providing an s3 bucket as  --conda-prefix does not seem to work.
