### ISSUE TITLE
Turn off  cloudwatch and costexplorer 

### ISSUE THREAD

**Issue by laurentiush** [4dn-dcic/tibanna#401]
Hi, 

I am running tibanna regularly, but am incurring quite some costs for 2 specific 'usage types': 
- EU-CW:MetricMonitorUsage (CloudWatch)
- USE1-APIRequest (Cost Explorer)

Now that my pipeline is up and running, I don't really need all the detailed information. Is there a way to turn off this logging and monitoring?

One option could be to remove the rights to access Cost Explorer, but I don't know if this will break tibanna:

https://repost.aws/questions/QUhjMTBYs2QGSFcgto3BdJMA/disable-aws-cost-explorer-permissions

**Comment by alexander-veit** [comment]
Hi,

currently there is no option to switch it off, but I agree that there should be one. I will look into it. 

I think that simply removing Tibanna's permissions to Cloudwatch will probably break it.

**Comment by laurentiush** [comment]
Thanks! Especially if you have a lot of small tasks those costs can quickly add up. 

At some point I tried grouping rules in snakemake to reduce the number of instances required, but somehow the output was not detected by snakemake after transferring it back to S3 and pipelines would always fail because of that.

**Comment by laurentiush** [comment]
Hi again,

I noticed that you have created a branch which addresses my question and was wondering if you plan to include those changes in a next release.

**Comment by alexander-veit** [comment]
Hi,

I started working on this some time ago but got distracted with other things. I will try to make some progress soon.

**Comment by laurentiush** [comment]
Thanks a lot! I see that it is now available.

**Comment by alexander-veit** [comment]
Yes, I still need to release the new version. I will do that today.
