### ISSUE TITLE
Retirement of G3 instances

### ISSUE THREAD

**Issue by laurentiush** [4dn-dcic/tibanna#411]
It seems that AWS has retired their G3 instances. Now it seems that in some cases Tibanna selects a g3 instance because it thinks it is the cheapest option (  I am using spot instances ). Result is that the job fails because the g3 instance does not exist anymore. 

Could you please update the list with available instances from which Tibanna chooses?

**Comment by alexander-veit** [comment]
Thank you for reporting this. @clarabakker Could you please investigate and remove the relevant instances from the Benchmark package?

**Comment by alexander-veit** [comment]
This should be resolved in version 5.5.0.

**Comment by laurentiush** [comment]
Thanks a lot!
